import { useState, useEffect, useMemo } from 'react'
import { supabase } from '../lib/supabase'
import { CAUSAS_SEED } from '../lib/seedData'
import { motion, AnimatePresence } from 'framer-motion'
const estadoConfig={vencido:{label:'VENCIDO',color:'#dc2626',bg:'#fef2f2',dot:'#dc2626'},proximo:{label:'POR VENCER',color:'#d97706',bg:'#fffbeb',dot:'#f59e0b'},apjo:{label:'APJO',color:'#7c3aed',bg:'#f5f3ff',dot:'#8b5cf6'},suspendida:{label:'SUSPENDIDA',color:'#6b7280',bg:'#f9fafb',dot:'#9ca3af'},vigente:{label:'VIGENTE',color:'#059669',bg:'#ecfdf5',dot:'#10b981'}}
const spring={type:'spring',stiffness:400,damping:30}
const springGentle={type:'spring',stiffness:280,damping:24}
const css=`@import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600&display=swap');*{box-sizing:border-box;margin:0;padding:0}body{font-family:'DM Sans',sans-serif;background:#f0f4f8;-webkit-font-smoothing:antialiased}input,select,textarea,button{font-family:'DM Sans',sans-serif}.badge{display:inline-flex;align-items:center;gap:5px;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:600;letter-spacing:0.3px}::-webkit-scrollbar{width:5px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:#cbd5e1;border-radius:10px}.input-focus:focus{border-color:#1e3a8a!important;box-shadow:0 0 0 3px rgba(30,58,138,0.08)!important;outline:none}.row-hover{transition:background 0.12s ease}.row-hover:hover{background:#eff6ff!important}`
export default function Dashboard({session}){
const [causas,setCausas]=useState([])
const [loading,setLoading]=useState(true)
const [seeding,setSeeding]=useState(false)
const [search,setSearch]=useState('')
const [filterTribunal,setFilterTribunal]=useState('')
const [filterEstado,setFilterEstado]=useState('')
const [modal,setModal]=useState(null)
const [activeTab,setActiveTab]=useState('datos')
const [editField,setEditField]=useState(null)
const [editValue,setEditValue]=useState('')
const [nuevaNota,setNuevaNota]=useState('')
const [notas,setNotas]=useState([])
const [audiencias,setAudiencias]=useState([])
const [showAudForm,setShowAudForm]=useState(false)
const [nuevaAud,setNuevaAud]=useState({fecha:'',tipo:'',resultado:'',notas:''})
const [saving,setSaving]=useState(false)
const [showNueva,setShowNueva]=useState(false)
const [nueva,setNueva]=useState({ruc:'',rit:'',tribunal:'',delito:'',imputado:'',fiscal:'',cautelar:'',centro_penal:'',plazo:'',estado:'vigente'})
useEffect(()=>{loadCausas()},[])
const loadCausas=async()=>{setLoading(true);const{data,error}=await supabase.from('causas').select('*').order('created_at',{ascending:false});if(!error)setCausas(data||[]);setLoading(false)}
const seedDatabase=async()=>{setSeeding(true);const chunks=[];for(let i=0;i<CAUSAS_SEED.length;i+=50)chunks.push(CAUSAS_SEED.slice(i,i+50));for(const chunk of chunks){await supabase.from('causas').insert(chunk.map(c=>({ruc:c.ruc,rit:c.rit,tribunal:c.tribunal,delito:c.delito,imputado:c.imputado,fiscal:'',cautelar:'',centro_penal:'',plazo:c.plazo,estado:c.estado,carpeta_ref:''})))}await loadCausas();setSeeding(false)}
const openModal=async(c)=>{setModal(c);setActiveTab('datos');const[{data:n},{data:a}]=await Promise.all([supabase.from('notas').select('*').eq('causa_id',c.id).order('created_at',{ascending:false}),supabase.from('audiencias').select('*').eq('causa_id',c.id).order('fecha',{ascending:false})]);setNotas(n||[]);setAudiencias(a||[])}
const closeModal=()=>{setModal(null);setEditField(null)}
const updateField=async(field,value)=>{setSaving(true);await supabase.from('causas').update({[field]:value,updated_at:new Date()}).eq('id',modal.id);const updated={...modal,[field]:value};setModal(updated);setCausas(prev=>prev.map(c=>c.id===updated.id?updated:c));setEditField(null);setSaving(false)}
const saveNota=async()=>{if(!nuevaNota.trim())return;setSaving(true);const{data}=await supabase.from('notas').insert({causa_id:modal.id,contenido:nuevaNota}).select().single();if(data)setNotas(prev=>[data,...prev]);setNuevaNota('');setSaving(false)}
const saveAudiencia=async()=>{if(!nuevaAud.fecha)return;setSaving(true);const{data}=await supabase.from('audiencias').insert({causa_id:modal.id,...nuevaAud}).select().single();if(data)setAudiencias(prev=>[data,...prev]);setNuevaAud({fecha:'',tipo:'',resultado:'',notas:''});setShowAudForm(false);setSaving(false)}
const saveCausa=async()=>{if(!nueva.ruc)return;setSaving(true);const{data}=await supabase.from('causas').insert(nueva).select().single();if(data){setCausas(prev=>[data,...prev]);setShowNueva(false);setNueva({ruc:'',rit:'',tribunal:'',delito:'',imputado:'',fiscal:'',cautelar:'',centro_penal:'',plazo:'',estado:'vigente'})};setSaving(false)}
const signOut=()=>supabase.auth.signOut()
const tribunales=useMemo(()=>[...new Set(causas.map(c=>c.tribunal).filter(Boolean))].sort(),[causas])
const filtered=useMemo(()=>causas.filter(c=>{const s=search.toLowerCase();const match=!s||[c.ruc,c.rit,c.imputado,c.delito,c.tribunal,c.fiscal].some(v=>v?.toLowerCase().includes(s));return match&&(!filterTribunal||c.tribunal===filterTribunal)&&(!filterEstado||c.estado===filterEstado)}),[causas,search,filterTribunal,filterEstado])
const stats=useMemo(()=>({total:causas.length,vencido:causas.filter(c=>c.estado==='vencido').length,proximo:causas.filter(c=>c.estado==='proximo').length,apjo:causas.filter(c=>c.estado==='apjo').length,vigente:causas.filter(c=>c.estado==='vigente').length}),[causas])
const C=modal?causas.find(x=>x.id===modal.id)||modal:null
const Badge=({estado})=>{const cfg=estadoConfig[estado]||estadoConfig.vigente;return(<span className="badge" style={{background:cfg.bg,color:cfg.color}}><span style={{width:6,height:6,borderRadius:'50%',background:cfg.dot,display:'inline-block'}}/>{cfg.label}</span>)}
const FieldRow=({label,fieldKey,editable,full})=>(<div style={{gridColumn:full?'1 / -1':'auto'}}><div style={{fontSize:10,color:'#94a3b8',textTransform:'uppercase',letterSpacing:1,marginBottom:5,fontWeight:600}}>{label}</div><AnimatePresence mode="wait">{editField===fieldKey?(<motion.div key="edit" initial={{opacity:0,y:-4}} animate={{opacity:1,y:0}} exit={{opacity:0,y:4}} transition={spring} style={{display:'flex',gap:8}}><input className="input-focus" style={{flex:1,padding:'9px 12px',border:'2px solid #1e3a8a',borderRadius:10,fontSize:14,background:'#fff'}} value={editValue} onChange={e=>setEditValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')updateField(fieldKey,editValue);if(e.key==='Escape')setEditField(null)}} autoFocus/><motion.button whileTap={{scale:0.94}} onClick={()=>updateField(fieldKey,editValue)} style={{background:'#1e3a8a',color:'#fff',border:'none',borderRadius:10,padding:'0 16px',cursor:'pointer',fontWeight:600}}>✓</motion.button><motion.button whileTap={{scale:0.94}} onClick={()=>setEditField(null)} style={{background:'#f1f5f9',color:'#64748b',border:'none',borderRadius:10,padding:'0 14px',cursor:'pointer'}}>✗</motion.button></motion.div>):(<motion.div key="view" initial={{opacity:0}} animate={{opacity:1}} whileHover={editable?{scale:1.005,backgroundColor:'#eff6ff'}:{}} onClick={()=>{if(editable){setEditField(fieldKey);setEditValue(C[fieldKey]||'')}}} style={{fontSize:14,color:'#1e293b',padding:'9px 13px',background:'#f8fafc',borderRadius:10,border:'1px solid #e2e8f0',minHeight:40,display:'flex',alignItems:'center',justifyContent:'space-between',cursor:editable?'pointer':'default',transition:'background 0.15s'}}><span style={{color:C[fieldKey]?'#1e293b':'#cbd5e1',fontStyle:C[fieldKey]?'normal':'italic'}}>{C[fieldKey]||(editable?'Clic para agregar...':'—')}</span>{editable&&<span style={{fontSize:12,color:'#c4cdd6'}}>✏</span>}</motion.div>)}</AnimatePresence></div>)
return(
<div style={{fontFamily:'DM Sans,sans-serif',background:'#f0f4f8',minHeight:'100vh'}}>
<style>{css}</style>
<motion.div initial={{y:-60,opacity:0}} animate={{y:0,opacity:1}} transition={springGentle} style={{background:'#0f172a',padding:'0 32px',height:60,display:'flex',alignItems:'center',justifyContent:'space-between',position:'sticky',top:0,zIndex:50,boxShadow:'0 1px 0 rgba(255,255,255,0.05)'}}>
<div style={{display:'flex',alignItems:'center',gap:12}}>
<motion.div whileHover={{rotate:[0,-8,8,0],transition:{duration:0.4}}} style={{width:34,height:34,background:'linear-gradient(135deg,#1e3a8a,#3b82f6)',borderRadius:10,display:'flex',alignItems:'center',justifyContent:'center',fontSize:18}}>⚖</motion.div>
<div><div style={{fontFamily:'Libre Baskerville,serif',color:'#fff',fontSize:15,fontWeight:700}}>Gestor de Causas Penales</div><div style={{color:'#475569',fontSize:10,letterSpacing:1.5,textTransform:'uppercase'}}>Sistema de Gestión Legal</div></div>
</div>
<div style={{display:'flex',alignItems:'center',gap:16}}>
<AnimatePresence>{saving&&<motion.span initial={{opacity:0,x:10}} animate={{opacity:1,x:0}} exit={{opacity:0,x:10}} style={{color:'#60a5fa',fontSize:12}}>● Guardando...</motion.span>}</AnimatePresence>
<span style={{color:'#475569',fontSize:12}}>{session.user.email}</span>
<motion.button whileHover={{scale:1.03}} whileTap={{scale:0.97}} onClick={signOut} style={{background:'transparent',border:'1px solid #334155',color:'#94a3b8',borderRadius:7,padding:'5px 14px',fontSize:12,cursor:'pointer'}}>Salir</motion.button>
</div>
</motion.div>
<div style={{padding:'28px 32px',maxWidth:1400,margin:'0 auto'}}>
<AnimatePresence>{stats.vencido>0&&(<motion.div initial={{opacity:0,y:-12,height:0}} animate={{opacity:1,y:0,height:'auto'}} exit={{opacity:0,height:0}} style={{background:'#fff',border:'1px solid #fca5a5',borderLeft:'4px solid #dc2626',borderRadius:12,padding:'14px 20px',marginBottom:24,display:'flex',alignItems:'center',gap:12,overflow:'hidden'}}><span style={{fontSize:22}}>🚨</span><div><div style={{fontWeight:600,color:'#dc2626',fontSize:14}}>{stats.vencido} causa{stats.vencido>1?'s':''} con plazo VENCIDO</div><div style={{color:'#9ca3af',fontSize:12,marginTop:2}}>Requieren revisión urgente</div></div></motion.div>)}</AnimatePresence>
<AnimatePresence>{causas.length===0&&!loading&&(<motion.div initial={{opacity:0,scale:0.97}} animate={{opacity:1,scale:1}} transition={springGentle} style={{background:'linear-gradient(135deg,#1e3a8a,#2563eb)',borderRadius:16,padding:'24px 28px',marginBottom:24,display:'flex',alignItems:'center',justifyContent:'space-between',boxShadow:'0 4px 24px rgba(30,58,138,0.28)'}}><div><div style={{fontFamily:'Libre Baskerville,serif',color:'#fff',fontSize:18,marginBottom:4}}>Base de datos vacía</div><div style={{color:'#93c5fd',fontSize:13}}>Importa tus {CAUSAS_SEED.length} causas con un clic</div></div><motion.button whileHover={{scale:1.04}} whileTap={{scale:0.97}} onClick={seedDatabase} disabled={seeding} style={{background:'#fff',color:'#1e3a8a',border:'none',borderRadius:12,padding:'12px 24px',fontSize:14,cursor:'pointer',fontWeight:700}}>{seeding?'⏳ Importando...':'📥 Importar causas'}</motion.button></motion.div>)}</AnimatePresence>
<div style={{display:'flex',gap:14,marginBottom:24,flexWrap:'wrap'}}>
{[{key:'',label:'Total causas',num:stats.total,color:'#1e3a8a',accent:'#3b82f6'},{key:'vigente',label:'Vigentes',num:stats.vigente,color:'#059669',accent:'#10b981'},{key:'vencido',label:'Vencidos',num:stats.vencido,color:'#dc2626',accent:'#ef4444'},{key:'proximo',label:'Por vencer',num:stats.proximo,color:'#d97706',accent:'#f59e0b'},{key:'apjo',label:'APJO',num:stats.apjo,color:'#7c3aed',accent:'#8b5cf6'}].map((st,i)=>{const active=filterEstado===st.key&&st.key!=='';return(<motion.div key={st.key} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{...springGentle,delay:i*0.06}} whileHover={{y:-3,boxShadow:'0 10px 28px rgba(0,0,0,0.1)'}} whileTap={{scale:0.97}} onClick={()=>setFilterEstado(filterEstado===st.key?'':st.key)} style={{background:active?st.color:'#fff',borderRadius:14,padding:'16px 22px',minWidth:120,border:`1px solid ${active?st.color:'#e2e8f0'}`,boxShadow:'0 1px 4px rgba(0,0,0,0.05)',cursor:'pointer'}}><div style={{fontSize:32,fontWeight:700,color:active?'#fff':st.color,lineHeight:1,fontFamily:'Libre Baskerville,serif'}}>{st.num}</div><div style={{fontSize:11,color:active?'rgba(255,255,255,0.75)':'#94a3b8',marginTop:4,textTransform:'uppercase',letterSpacing:0.8,fontWeight:600}}>{st.label}</div>{!active&&<div style={{height:2,background:st.accent,borderRadius:2,marginTop:10,width:28}}/>}</motion.div>)})}
</div>
<motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:0.3}} style={{display:'flex',gap:10,marginBottom:16,flexWrap:'wrap',alignItems:'center'}}>
<div style={{flex:1,minWidth:260,position:'relative'}}><span style={{position:'absolute',left:13,top:'50%',transform:'translateY(-50%)',color:'#94a3b8',fontSize:14,pointerEvents:'none'}}>🔍</span><input className="input-focus" style={{width:'100%',padding:'10px 14px 10px 38px',border:'1px solid #e2e8f0',borderRadius:11,fontSize:14,background:'#fff',boxShadow:'0 1px 3px rgba(0,0,0,0.04)'}} placeholder="Buscar por RUC, RIT, imputado, delito, tribunal..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
<select className="input-focus" style={{padding:'10px 14px',border:'1px solid #e2e8f0',borderRadius:11,fontSize:13,background:'#fff',cursor:'pointer',color:'#475569'}} value={filterTribunal} onChange={e=>setFilterTribunal(e.target.value)}><option value="">Todos los tribunales</option>{tribunales.map(t=><option key={t} value={t}>{t}</option>)}</select>
<select className="input-focus" style={{padding:'10px 14px',border:'1px solid #e2e8f0',borderRadius:11,fontSize:13,background:'#fff',cursor:'pointer',color:'#475569'}} value={filterEstado} onChange={e=>setFilterEstado(e.target.value)}><option value="">Todos los estados</option>{Object.entries(estadoConfig).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select>
<span style={{fontSize:13,color:'#94a3b8'}}>{filtered.length} resultado{filtered.length!==1?'s':''}</span>
<motion.button whileHover={{scale:1.03,boxShadow:'0 4px 16px rgba(30,58,138,0.28)'}} whileTap={{scale:0.97}} onClick={()=>setShowNueva(true)} style={{background:'#1e3a8a',color:'#fff',border:'none',borderRadius:11,padding:'10px 20px',fontSize:13,cursor:'pointer',fontWeight:600,whiteSpace:'nowrap'}}>+ Nueva causa</motion.button>
</motion.div>
{loading?(<motion.div initial={{opacity:0}} animate={{opacity:1}} style={{textAlign:'center',padding:80,color:'#94a3b8'}}><motion.div animate={{rotate:360}} transition={{duration:1.2,repeat:Infinity,ease:'linear'}} style={{fontSize:28,display:'inline-block',marginBottom:12}}>⚖</motion.div><div style={{fontSize:15}}>Cargando causas...</div></motion.div>):(
<motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:0.2}} style={{background:'#fff',borderRadius:16,boxShadow:'0 1px 6px rgba(0,0,0,0.06)',overflow:'hidden',border:'1px solid #e2e8f0'}}>
<table style={{width:'100%',borderCollapse:'collapse'}}>
<thead><tr>{['RUC','RIT','Tribunal','Imputado','Delito','Fiscal','Plazo','Estado',''].map(h=>(<th key={h} style={{padding:'13px 16px',textAlign:'left',fontSize:11,fontWeight:600,color:'#64748b',letterSpacing:0.8,textTransform:'uppercase',background:'#f8fafc',borderBottom:'2px solid #e2e8f0'}}>{h}</th>))}</tr></thead>
<tbody><AnimatePresence>{filtered.map((c,idx)=>(<motion.tr key={c.id} className="row-hover" initial={{opacity:0,x:-10}} animate={{opacity:1,x:0}} transition={{delay:idx*0.02,...spring}} style={{background:idx%2===0?'#fff':'#fafbfc',borderBottom:'1px solid #f1f5f9'}}>
<td style={{padding:'12px 16px',fontSize:12,fontFamily:'monospace',fontWeight:700,color:'#1e3a8a'}}>{c.ruc}</td>
<td style={{padding:'12px 16px',fontSize:12,color:'#64748b'}}>{c.rit||'—'}</td>
<td style={{padding:'12px 16px',fontSize:12,color:'#475569'}}>{c.tribunal}</td>
<td style={{padding:'12px 16px',fontSize:13}}><div style={{maxWidth:200,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',color:'#1e293b'}} title={c.imputado}>{c.imputado}</div></td>
<td style={{padding:'12px 16px',fontSize:12}}><div style={{maxWidth:180,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',color:'#475569'}} title={c.delito}>{c.delito||'—'}</div></td>
<td style={{padding:'12px 16px',fontSize:12,color:c.fiscal?'#1e293b':'#cbd5e1',fontStyle:c.fiscal?'normal':'italic'}}>{c.fiscal||'Sin asignar'}</td>
<td style={{padding:'12px 16px',fontSize:11}}><div style={{maxWidth:130,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',color:'#64748b'}}>{c.plazo||'—'}</div></td>
<td style={{padding:'12px 16px'}}><Badge estado={c.estado}/></td>
<td style={{padding:'12px 16px'}}><motion.button whileHover={{scale:1.06,background:'#1e3a8a',color:'#fff'}} whileTap={{scale:0.95}} onClick={()=>openModal(c)} style={{background:'#eff6ff',color:'#1e3a8a',border:'1px solid #bfdbfe',borderRadius:8,padding:'5px 14px',fontSize:12,cursor:'pointer',fontWeight:600,whiteSpace:'nowrap',transition:'background 0.15s,color 0.15s'}}>Ver →</motion.button></td>
</motion.tr>))}</AnimatePresence></tbody>
</table>
{filtered.length===0&&<div style={{textAlign:'center',padding:60,color:'#94a3b8',fontSize:15}}>Sin resultados.</div>}
</motion.div>)}
</div>
<AnimatePresence>{modal&&C&&(<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={e=>e.target===e.currentTarget&&closeModal()} style={{position:'fixed',inset:0,background:'rgba(15,23,42,0.65)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:200,padding:24,backdropFilter:'blur(8px)'}}>
<motion.div initial={{opacity:0,scale:0.94,y:24}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:0.94,y:16}} transition={springGentle} style={{background:'#fff',borderRadius:20,width:'100%',maxWidth:800,maxHeight:'90vh',overflow:'hidden',boxShadow:'0 32px 80px rgba(0,0,0,0.35)',display:'flex',flexDirection:'column'}}>
<div style={{background:'linear-gradient(135deg,#0f172a 0%,#1e3a8a 100%)',padding:'22px 28px',display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}>
<div><div style={{fontFamily:'Libre Baskerville,serif',color:'#fff',fontSize:19,marginBottom:5}}>RUC: {C.ruc}</div><div style={{color:'#93c5fd',fontSize:13}}>RIT: {C.rit||'—'} · {C.tribunal}</div></div>
<div style={{display:'flex',alignItems:'center',gap:12}}><Badge estado={C.estado}/><motion.button whileHover={{scale:1.1,background:'rgba(255,255,255,0.2)'}} whileTap={{scale:0.9}} onClick={closeModal} style={{background:'rgba(255,255,255,0.1)',border:'none',color:'#fff',borderRadius:10,width:34,height:34,cursor:'pointer',fontSize:20,display:'flex',alignItems:'center',justifyContent:'center'}}>×</motion.button></div>
</div>
<div style={{display:'flex',borderBottom:'1px solid #f1f5f9',background:'#fafafa',padding:'0 28px'}}>
{[['datos','📋 Datos'],['notas','📝 Notas'],['audiencias','📅 Audiencias'],['carpeta','📁 Carpeta']].map(([k,l])=>(<motion.button key={k} onClick={()=>setActiveTab(k)} whileTap={{scale:0.97}} style={{padding:'13px 18px',fontSize:13,fontWeight:activeTab===k?600:400,color:activeTab===k?'#1e3a8a':'#94a3b8',borderBottom:`2px solid ${activeTab===k?'#1e3a8a':'transparent'}`,marginBottom:-1,background:'none',border:'none',borderBottomWidth:2,borderBottomStyle:'solid',borderBottomColor:activeTab===k?'#1e3a8a':'transparent',cursor:'pointer',transition:'color 0.15s'}}>{l}</motion.button>))}
</div>
<div style={{padding:'24px 28px',overflowY:'auto',flex:1}}>
<AnimatePresence mode="wait"><motion.div key={activeTab} initial={{opacity:0,x:8}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-8}} transition={{duration:0.18}}>
{activeTab==='datos'&&(<div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><FieldRow label="Imputado(s)" fieldKey="imputado" full/><FieldRow label="Delito" fieldKey="delito" full/><FieldRow label="Tribunal" fieldKey="tribunal"/><FieldRow label="RIT" fieldKey="rit"/><FieldRow label="Fiscal" fieldKey="fiscal" editable/><FieldRow label="Cautelar Procesal" fieldKey="cautelar" editable/><FieldRow label="Centro Penal" fieldKey="centro_penal" editable/><FieldRow label="Plazo" fieldKey="plazo" editable full/></div><div style={{marginTop:20}}><div style={{fontSize:10,color:'#94a3b8',textTransform:'uppercase',letterSpacing:1,marginBottom:8,fontWeight:600}}>Estado Procesal</div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{Object.entries(estadoConfig).map(([k,v])=>(<motion.button key={k} whileHover={{scale:1.04}} whileTap={{scale:0.96}} onClick={()=>updateField('estado',k)} style={{padding:'7px 16px',borderRadius:20,fontSize:12,cursor:'pointer',fontWeight:600,border:`1.5px solid ${v.color}`,background:C.estado===k?v.color:'#fff',color:C.estado===k?'#fff':v.color,transition:'all 0.15s'}}>{v.label}</motion.button>))}</div></div></div>)}
{activeTab==='notas'&&(<div>{notas.length===0&&<p style={{color:'#94a3b8',fontSize:13,marginBottom:16}}>Sin notas aún.</p>}<AnimatePresence>{notas.map(n=>(<motion.div key={n.id} initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}} style={{background:'#f8fafc',borderRadius:12,padding:'13px 16px',marginBottom:10,border:'1px solid #e2e8f0'}}><div style={{fontSize:11,color:'#94a3b8',marginBottom:6,fontWeight:600}}>{new Date(n.created_at).toLocaleString('es-CL')}</div><div style={{fontSize:14,color:'#1e293b',whiteSpace:'pre-wrap',lineHeight:1.6}}>{n.contenido}</div></motion.div>))}</AnimatePresence><div style={{marginTop:16}}><textarea className="input-focus" style={{width:'100%',padding:13,fontSize:14,border:'1px solid #e2e8f0',borderRadius:12,minHeight:100,resize:'vertical',background:'#fff'}} placeholder="Escribir nueva nota..." value={nuevaNota} onChange={e=>setNuevaNota(e.target.value)}/><motion.button whileHover={{scale:1.03}} whileTap={{scale:0.97}} onClick={saveNota} disabled={saving} style={{marginTop:10,background:'#1e3a8a',color:'#fff',border:'none',borderRadius:10,padding:'10px 20px',fontSize:13,cursor:'pointer',fontWeight:600}}>{saving?'Guardando...':'+ Agregar nota'}</motion.button></div></div>)}
{activeTab==='audiencias'&&(<div>{audiencias.length===0&&!showAudForm&&<p style={{color:'#94a3b8',fontSize:13,marginBottom:16}}>Sin audiencias registradas.</p>}<AnimatePresence>{audiencias.map(a=>(<motion.div key={a.id} initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,height:0}} style={{background:'#f8fafc',borderRadius:12,padding:'13px 16px',marginBottom:10,border:'1px solid #e2e8f0'}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:4}}><strong style={{fontSize:14,color:'#1e293b'}}>{a.tipo||'Audiencia'}</strong><span style={{fontSize:12,color:'#94a3b8',background:'#f1f5f9',padding:'2px 10px',borderRadius:20}}>{a.fecha}</span></div>{a.resultado&&<div style={{fontSize:13,color:'#475569',marginTop:4}}>Resultado: {a.resultado}</div>}{a.notas&&<div style={{fontSize:12,color:'#94a3b8',marginTop:4}}>{a.notas}</div>}</motion.div>))}</AnimatePresence><AnimatePresence>{showAudForm&&(<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}} style={{background:'#f8fafc',padding:16,borderRadius:12,border:'1px solid #e2e8f0',marginBottom:14,overflow:'hidden'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginBottom:12}}>{[['fecha','Fecha','date'],['tipo','Tipo','text'],['resultado','Resultado','text'],['notas','Observaciones','text']].map(([k,l,t])=>(<div key={k}><div style={{fontSize:10,color:'#94a3b8',textTransform:'uppercase',letterSpacing:0.8,marginBottom:4,fontWeight:600}}>{l}</div><input type={t} className="input-focus" style={{width:'100%',padding:'9px 12px',border:'1px solid #e2e8f0',borderRadius:8,fontSize:13,boxSizing:'border-box'}} value={nuevaAud[k]} onChange={e=>setNuevaAud(p=>({...p,[k]:e.target.value}))}/></div>))}</div><div style={{display:'flex',gap:8}}><motion.button whileTap={{scale:0.97}} onClick={saveAudiencia} disabled={saving} style={{background:'#1e3a8a',color:'#fff',border:'none',borderRadius:9,padding:'8px 18px',fontSize:13,cursor:'pointer',fontWeight:600}}>{saving?'Guardando...':'Guardar'}</motion.button><motion.button whileTap={{scale:0.97}} onClick={()=>setShowAudForm(false)} style={{background:'#f1f5f9',color:'#64748b',border:'none',borderRadius:9,padding:'8px 16px',fontSize:13,cursor:'pointer'}}>Cancelar</motion.button></div></motion.div>)}</AnimatePresence>{!showAudForm&&<motion.button whileHover={{scale:1.03}} whileTap={{scale:0.97}} onClick={()=>setShowAudForm(true)} style={{background:'#1e3a8a',color:'#fff',border:'none',borderRadius:10,padding:'10px 20px',fontSize:13,cursor:'pointer',fontWeight:600}}>+ Nueva audiencia</motion.button>}</div>)}
{activeTab==='carpeta'&&(<div><div style={{marginBottom:20}}><div style={{fontSize:10,color:'#94a3b8',textTransform:'uppercase',letterSpacing:1,marginBottom:5,fontWeight:600}}>Referencia Carpeta Física</div><AnimatePresence mode="wait">{editField==='carpeta_ref'?(<motion.div key="edit" initial={{opacity:0}} animate={{opacity:1}} style={{display:'flex',gap:8}}><input className="input-focus" style={{flex:1,padding:'9px 12px',border:'2px solid #1e3a8a',borderRadius:10,fontSize:14}} value={editValue} onChange={e=>setEditValue(e.target.value)} placeholder="Ej: Caja 3, Carpeta 12" autoFocus/><motion.button whileTap={{scale:0.94}} onClick={()=>updateField('carpeta_ref',editValue)} style={{background:'#1e3a8a',color:'#fff',border:'none',borderRadius:10,padding:'0 16px',cursor:'pointer'}}>✓</motion.button><motion.button whileTap={{scale:0.94}} onClick={()=>setEditField(null)} style={{background:'#f1f5f9',color:'#64748b',border:'none',borderRadius:10,padding:'0 14px',cursor:'pointer'}}>✗</motion.button></motion.div>):(<motion.div key="view" whileHover={{backgroundColor:'#eff6ff'}} onClick={()=>{setEditField('carpeta_ref');setEditValue(C.carpeta_ref||'')}} style={{fontSize:14,color:'#1e293b',padding:'9px 13px',background:'#f8fafc',borderRadius:10,border:'1px solid #e2e8f0',display:'flex',justifyContent:'space-between',cursor:'pointer',transition:'background 0.15s'}}><span style={{color:C.carpeta_ref?'#1e293b':'#cbd5e1',fontStyle:C.carpeta_ref?'normal':'italic'}}>{C.carpeta_ref||'Clic para ingresar ubicación...'}</span><span style={{fontSize:12,color:'#c4cdd6'}}>✏</span></motion.div>)}</AnimatePresence></div><motion.div whileHover={{borderColor:'#93c5fd',background:'#f0f7ff'}} transition={{duration:0.2}} style={{background:'#f8fafc',borderRadius:14,border:'2px dashed #cbd5e1',padding:40,textAlign:'center'}}><div style={{fontSize:48,marginBottom:12}}>📁</div><div style={{fontSize:15,color:'#475569',marginBottom:6,fontWeight:500}}>Documentos digitalizados</div><div style={{fontSize:12,color:'#94a3b8',marginBottom:20}}>Subida de PDFs e imágenes — próximamente</div><motion.button whileHover={{scale:1.04}} whileTap={{scale:0.96}} style={{background:'#1e3a8a',color:'#fff',border:'none',borderRadius:10,padding:'10px 22px',fontSize:13,cursor:'pointer',fontWeight:600,opacity:0.6}}>📎 Subir documento</motion.button></div></div>)}
</motion.div></AnimatePresence>
</div>
</motion.div>
</motion.div>)}</AnimatePresence>
<AnimatePresence>{showNueva&&(<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={e=>e.target===e.currentTarget&&setShowNueva(false)} style={{position:'fixed',inset:0,background:'rgba(15,23,42,0.65)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:200,padding:24,backdropFilter:'blur(8px)'}}>
<motion.div initial={{opacity:0,scale:0.94,y:24}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:0.94,y:16}} transition={springGentle} style={{background:'#fff',borderRadius:20,width:'100%',maxWidth:520,maxHeight:'90vh',overflowY:'auto',boxShadow:'0 32px 80px rgba(0,0,0,0.35)'}}>
<div style={{background:'linear-gradient(135deg,#0f172a,#1e3a8a)',padding:'20px 28px',display:'flex',justifyContent:'space-between',alignItems:'center',borderRadius:'20px 20px 0 0'}}><div style={{fontFamily:'Libre Baskerville,serif',color:'#fff',fontSize:18}}>Nueva Causa</div><motion.button whileHover={{scale:1.1}} whileTap={{scale:0.9}} onClick={()=>setShowNueva(false)} style={{background:'rgba(255,255,255,0.1)',border:'none',color:'#fff',borderRadius:10,width:34,height:34,cursor:'pointer',fontSize:20,display:'flex',alignItems:'center',justifyContent:'center'}}>×</motion.button></div>
<div style={{padding:'24px 28px'}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>{[{key:'ruc',label:'RUC *',placeholder:'Ej: 2600123456-7',full:true},{key:'rit',label:'RIT',placeholder:'Ej: 1234-2026'},{key:'tribunal',label:'Tribunal',placeholder:'Ej: 7 JG STGO'},{key:'imputado',label:'Imputado',placeholder:'Nombre completo',full:true},{key:'delito',label:'Delito',placeholder:'Tipo de delito',full:true},{key:'fiscal',label:'Fiscal',placeholder:'Nombre del fiscal'},{key:'cautelar',label:'Cautelar',placeholder:'Prisión preventiva...'},{key:'plazo',label:'Plazo',placeholder:'VENCE DD-MM-YYYY',full:true}].map(f=>(<div key={f.key} style={{gridColumn:f.full?'1 / -1':'auto'}}><div style={{fontSize:10,color:'#94a3b8',textTransform:'uppercase',letterSpacing:1,marginBottom:5,fontWeight:600}}>{f.label}</div><input className="input-focus" style={{width:'100%',padding:'9px 12px',border:'1px solid #e2e8f0',borderRadius:10,fontSize:13,boxSizing:'border-box',background:'#f8fafc'}} placeholder={f.placeholder} value={nueva[f.key]} onChange={e=>setNueva(p=>({...p,[f.key]:e.target.value}))}/></div>))}<div style={{gridColumn:'1 / -1'}}><div style={{fontSize:10,color:'#94a3b8',textTransform:'uppercase',letterSpacing:1,marginBottom:5,fontWeight:600}}>Estado</div><select className="input-focus" style={{width:'100%',padding:'9px 12px',border:'1px solid #e2e8f0',borderRadius:10,fontSize:13,background:'#f8fafc'}} value={nueva.estado} onChange={e=>setNueva(p=>({...p,estado:e.target.value}))}>{Object.entries(estadoConfig).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></div></div><div style={{display:'flex',gap:10,marginTop:20}}><motion.button whileHover={{scale:1.03}} whileTap={{scale:0.97}} onClick={saveCausa} disabled={saving||!nueva.ruc} style={{background:'#1e3a8a',color:'#fff',border:'none',borderRadius:10,padding:'11px 22px',fontSize:14,cursor:'pointer',fontWeight:600}}>{saving?'Guardando...':'Guardar causa'}</motion.button><motion.button whileHover={{scale:1.02}} whileTap={{scale:0.97}} onClick={()=>setShowNueva(false)} style={{background:'#f1f5f9',color:'#64748b',border:'none',borderRadius:10,padding:'11px 18px',fontSize:14,cursor:'pointer'}}>Cancelar</motion.button></div></div>
</motion.div>
</motion.div>)}</AnimatePresence>
</div>
)
}